version: '3'
services:
  mysql:
    image: mysql:5.6
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode=''
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: point
      TZ: Asia/Seoul

  redis:
    image: redis
    container_name: redis
    command: redis-server --port 6379
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=changeme
    restart: always
    ports:
      - 6379:6379