server:
  error:
    include-exception: false
    include-stacktrace: never

spring:
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextCredentialsAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextResourceLoaderAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.mail.MailSenderAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.cache.ElastiCacheAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.messaging.MessagingAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.jdbc.AmazonRdsDatabaseAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.metrics.CloudWatchExportAutoConfiguration

---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/point?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root

    jpa:
      database: mysql
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          jdbc:
            batch_size: 200
          order_inserts: true
          order_updates: true
          enable_lazy_load_no_tran: true
        hibernate.format_sql: true
  jackson:
    deserialization:
      adjust_dates_to_context_time_zone: false

cloud:
  aws:
    stack:
      auto: false
    region:
      auto: false
      static: ap-northeast-2
    ### sqs 설정을 추가해주세요. ###
    sqs:
      endpoint:
      name:
      group:
        id:
      core-thread-count:
      max-thread-count:
      queue-capacity: